### ISSUE TITLE
Can you provide some example?

### ISSUE THREAD

**Issue by reddingit** [meetanthony/crccsharp#1]
I'm new to C#, can you provide some example? thanks
@meetanthony

**Comment by meetanthony** [comment]
// Generating random data
var bytes = new byte[256];
System.Random random = new System.Random((int)System.DateTime.UtcNow.Ticks);
random.NextBytes(bytes);

// Initializing calculator with specific algorithm
CRC.Crc crc = new CRC.Crc(CRC.CrcStdParams.StandartParameters[CRC.CrcAlgorithms.Crc16Maxim]);

// Calculating CRC
uint crcResult = CRC.CrcHelper.ToUInt32(crc.ComputeHash(bytes));
