### ISSUE TITLE
Is that a bug?

### ISSUE THREAD

**Issue by ViniciusCalil** [meetanthony/crccsharp#2]
I wrote my own version of CRC algorithm and _experienced a problem when the Input string has an odd number of digits_ (I work with hexadecimal type of string). But when Input has an even number off charracters, my algorithm works well.
I tried a simple test and did the calculations by hand. The result points that maybe there is bug in algorithm of site http://crccalc.com/   (either I am not knowing how to calculate CRC yet) .

WHAT IS WORNG ? (Is its my test bellow or a bug?) 

(Try to copy and paste lines bellow to a text editor with nomospaced fonts to easy view.) 

Input String: C23
String Type: Hexadecinal characters
Input Bitstream: 0xC23

CRC version: CRC-8/CDMA2000

Polynomial: 0x9B
Init: 0xFF

Bitstream:
    1100 0010 0011

Start of calculation process:

    11000010001100000000             <:= Original Input bitstream plus excess remainder (0000 0000)
Xor 11111111  <:= Init (FF)          <:= CRC Initial value Xored to first byte of bitstream and the rest of bitstream
 ______________
    00111101001100000000             <:= CRC Remainder and the rest of bitstream
    ..111101001   		     <:= shift 2 bits and include 3 bits from the rest of bitstream 
 Xor..110011011    <:= Polynomial(9B) 
   ______________   
    ...01110010100000000             <:= CRC Remainder and the rest of bitstream
    ....111001010   		     <:= shift 1 bit and include 2 bits from the rest of bitstream 
    Xor 110011011    <:= Polynomial(9B) 
      ______________
    .....010100010000000             <:= CRC Remainder and the rest of bitstream
    ......101000100                  <:= shift 1 bit and include 2 bits from the rest of bitstream 
      Xor 110011011    <:= Polynomial(9B) 
        ______________
    .......1101111100000             <:= CRC Remainder and the rest of bitstream
    .......110111110                 <:= NO shift but include 1 bit from the rest of bitstream 
       Xor 110011011    <:= Polynomial(9B) 
         ______________
    ........001001010000             <:= CRC Remainder and the rest of bitstream 
    ..........100101000              <:= shift 2 bits and include 3 bits from the rest of bitstream 
         Xor  110011011    <:= Polynomial(9B) 
           ______________
    ...........101100110             <:= CRC Remainder and the rest of bitstream 
    ...........101100110             <:= NO shift but include 1 bit from the rest of bitstream 
           Xor 110011011    <:= Polynomial(9B) 
             ______________
    ............11111101    <:= CRC = 0xFD    

Or using a different  view approach:

Start of calculation process:

    1100 0010  [0011 (0000 0000)]    <:= Original Input bitstream plus excess remainder (0000 0000)
Xor 1111 1111  <:= Init (FF)         <:= CRC Initial value Xored to first byte of bitstream and the rest of bitstream 
 ______________
    0011 1101  [0011 (0000 0000)]    <:= CRC Remainder and rest of bitstream
      1 1110 1001   		     <:= shift 2 bits and include 3 bits from the rest of bitstream 
 Xor (1)1001 1011    <:= Polynomial(9B) 
    ______________   
        0111 0010  [1 (0000 0000)]   <:= CRC Remainder and rest of bitstream
         1 1100 1010   		     <:= shift 1 bit and include 2 bits from the rest of bitstream 
    Xor (1)1001 1011    <:= Polynomial(9B) 
       ______________
           0101 0001 [000 0000]      <:= CRC Remainder and rest of bitstream
            1 0100 0100              <:= shift 1 bit and include 2 bits from the rest of bitstream 
       Xor (1)1001 1011    <:= Polynomial(9B) 
          ______________
              1101 1111  [0 0000]    <:= CRC Remainder and rest of bitstream
              1 1011 1110            <:= NO shift but include 1 bit from the rest of bitstream 
         Xor (1)1001 1011    <:= Polynomial(9B) 
            ______________
                0010 0101  [0000]    <:= CRC Remainder and rest of bitstream 
                  1 0010 1000        <:= shift 2 bits and include 3 bits from the rest of bitstream 
             Xor (1)1001 1011    <:= Polynomial(9B) 
                ______________
                    1011 0011  [0]     <:= CRC Remainder and rest of bitstream 
                    1 0110 0110        <:= shift 2 bits and include 3 bits from the rest of bitstream 
               Xor (1)1001 1011    <:= Polynomial(9B) 
                  ______________
                      1111 1101    <:= CRC = 0xFD

**Comment by meetanthony** [comment]
http://crccalc.com/?crc=0C23&method=crc8&datatype=hex
result = 0x0B for CRC-8/CDMA2000

http://www.sunshine2k.de/coding/javascript/crc/crc_js.html
select CRC8_CDMA2000
Input: 0x0c 0x23
Result = 0xB

The test result is also correct.

I think there is no error.

**Comment by ViniciusCalil** [comment]
Thanks a lot, meetanthony.

**NO BUG**.

I got it. The algorithm of the those sites ([http://crccalc.com/?crc=0C23&method=crc8&datatype=hex](url)  and [http://www.sunshine2k.de/coding/javascript/crc/crc_js.html](url) ) are based on **BYTE** stream. My algorithm is based on **BIT** stream.

So working in those sites anyone must enter an Input String of size equal to a multiple of  8 bits like 0x**0**C23 ( 0000.1100.0010.0011_B) but in my algorithm I entered a string of 3 nibbles (3 groups of four bits) 0xC23 (1100.0010.0011_B). This is the answer, the BIT STREAMs are different.
