### ISSUE TITLE
Using BitConvert to determine Endian-ness of bytes

### ISSUE THREAD

**Issue by lukeperkins** [meetanthony/crccsharp#3]
Would it be possible to establish the Endianness through a property established in the Crc class or the Parameters class?
Most of the CRC computations I perform are cross platform and setting a global .NET static class, BitConverter, can be problematic. I use BitConverter in numerous other libraries and when the Endianness is changed at the global level, it changes the Endianness through the application.

**Comment by meetanthony** [comment]
I apologize that I did not pay attention to the problem you indicated for a long time.
In the latest version of the library, the byte order is the same as in the System.BitConverter class.
