### ISSUE TITLE
Possible problem with endian-ness

### ISSUE THREAD

**Issue by mikeasharp** [meetanthony/crccsharp#4]
I have compiled your DLL, and tested it:

```
crc = new CRC.Crc(CRC.CrcStdParams.StandartParameters[CRC.CrcAlgorithms.Crc16Arc]);

byte[] test = new byte[4] { 0x5e, 0x00, 0x06, 0x52 };
byte[] testcrc = crc.ComputeHash(test);
```

the correct CRC result 0xb591 is in array position 6 and 7.

`uint16 crcResult = CRC.CrcHelper.ToUInt16(crc.ComputeHash(bytes));`

Returns 0x0000

Probably as the value should be in array position 0 and 1, not 6 and 7.

Can you assist?

thanks

**Comment by meetanthony** [comment]
Yes you are right. Most likely, the returned value should be in byte order corresponding to that used in the System.BitConverter class. I will make changes to the code soon.

**Comment by meetanthony** [comment]
Fixed
