### ISSUE TITLE
What is the correct result to expect for zero length CRC checks ?

### ISSUE THREAD

**Issue by nurquhar** [meetanthony/crccsharp#5]
Sorry to raise this as an issue as it probably is not. I asked this question on stackoverflow : https://stackoverflow.com/questions/61385241/what-is-the-correct-crc-value-for-a-zero-length-check

Essentially I used you online tool which I like very much to check if my CRC functions are doing the correct thing. I am not CRC expert so I am not sure what is the correct result you should get for a check on a string which has zero length.

I hope you could post an informative comment.

**Comment by meetanthony** [comment]
Thanks for the question.
Actually, this is a mistake in the implementation of the checksum calculation algorithm on the site.
The function for splitting text into character codes for a null string returned an array with the element "0" (like "new byte [] {0}" in C #). Now this situation is processed as it should and incorrect calculation results are not displayed.
For a zero array there will be approximately the following sequence of actions:

```
$crc = $crcParams->Init;
$crc = $crc ^ $crcParams->XorOut;
```

But in fact, you still need to consider the parameters RefIn and RefOut. They invert the initialization value at the beginning (RefIn), and also invert the result at the end (RefOut). Hope that helped you.

**Comment by nurquhar** [comment]
Dear Anton

 

Thanks for the clarification, I see the website now handles zero length input with a ‘the computer says no’.

 

Regards

Neil
